### PR TITLE
Ice 3.6.5, Python 2.7 and 3.6

### PR DESCRIPTION
**Pull request by manics**
Updates Ice to 3.6.5
Adds Python 3.6 wheel

### CODE REVIEW

**Comment by joshmoore** [comment]
Simple testing looks good:

```
[root@6497069fb944 src]# export PATH=/opt/rh/rh-python36/root/bin/:$PATH
[root@6497069fb944 src]# cd /dist
[root@6497069fb944 dist]# ls -ltra
total 68204
-rw-r--r-- 1 root root 34907833 Sep  4 19:17 zeroc_ice-3.6.5-cp27-cp27mu-manylinux2010_x86_64.whl
drwxr-xr-x 2 root root      123 Sep  4 19:24 .
-rw-r--r-- 1 root root 34923496 Sep  4 19:24 zeroc_ice-3.6.5-cp36-cp36m-manylinux2010_x86_64.whl
drwxr-xr-x 1 root root     4096 Sep  4 19:26 ..
[root@6497069fb944 dist]# pip install zeroc_ice-3.6.5-cp36-cp36m-manylinux2010_x86_64.whl
zeroc_ice-3.6.5-cp36-cp36m-manylinux2010_x86_64.whl is not a supported wheel on this platform.
You are using pip version 9.0.1, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[root@6497069fb944 dist]# pip install -U pip
Cache entry deserialization failed, entry ignored
Collecting pip
  Downloading https://files.pythonhosted.org/packages/30/db/9e38760b32e3e7f40cce46dd5fb107b8c73840df38f0046d8e6514e675a1/pip-19.2.3-py2.py3-none-any.whl (1.4MB)
    100% |████████████████████████████████| 1.4MB 892kB/s
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Uninstalling pip-9.0.1:
      Successfully uninstalled pip-9.0.1
Successfully installed pip-19.2.3
[root@6497069fb944 dist]# pip install zeroc_ice-3.6.5-cp36-cp36m-manylinux2010_x86_64.whl
Processing ./zeroc_ice-3.6.5-cp36-cp36m-manylinux2010_x86_64.whl
Installing collected packages: zeroc-ice
Successfully installed zeroc-ice-3.6.5
[root@6497069fb944 dist]# python
Python 3.6.3 (default, May 31 2019, 13:05:43)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Ice
>>> Ice.stringVersion()
'3.6.5'
>>>
(no segfault)
```

**Comment by joshmoore** [comment]
Re-opening to activate travis.

**Comment by joshmoore** [comment]
Ran for 25 minutes. Propose release as 0.1.0.

Is a Python3 version of zeroc-ice-py-centos7 still needed?

**Comment by manics** [comment]
The main differences are:
- this requires an updated pip so on centos7 can't be installed globally
- this bundles a static copy of openssl so needs to be updated if there's a critical openssl update

For now probably safer to keep the centos7 specific build for production use until we've tested the manylinux build a bit more.

**Comment by joshmoore** [comment]
Understood. Still merging, tagging as 0.1.0, and using for the initial tox test setups while we investigate the segfault on https://github.com/ome/zeroc-ice-py-centos7/pull/3#issuecomment-528261975

**Pull request merged**
